declare module 'lucide-react' {
  import { ComponentType, SVGProps } from 'react'
  
  export interface LucideProps extends SVGProps<SVGSVGElement> {
    size?: string | number
    color?: string
    strokeWidth?: string | number
  }
  
  export const Users: ComponentType<LucideProps>
  export const BookOpen: ComponentType<LucideProps>
  export const BarChart3: ComponentType<LucideProps>
  export const Settings: ComponentType<LucideProps>
  export const Eye: ComponentType<LucideProps>
  export const Edit: ComponentType<LucideProps>
  export const Trash2: ComponentType<LucideProps>
  export const Plus: ComponentType<LucideProps>
  export const Search: ComponentType<LucideProps>
  export const TrendingUp: ComponentType<LucideProps>
  export const Activity: ComponentType<LucideProps>
  export const Database: ComponentType<LucideProps>
  export const Stethoscope: ComponentType<LucideProps>
  export const FileText: ComponentType<LucideProps>
  export const Clock: ComponentType<LucideProps>
  export const CheckCircle: ComponentType<LucideProps>
  export const AlertCircle: ComponentType<LucideProps>
  export const User: ComponentType<LucideProps>
  export const Heart: ComponentType<LucideProps>
  export const Brain: ComponentType<LucideProps>
  export const Send: ComponentType<LucideProps>
  export const Mic: ComponentType<LucideProps>
  export const MicOff: ComponentType<LucideProps>
  export const Video: ComponentType<LucideProps>
  export const VideoOff: ComponentType<LucideProps>
  export const Phone: ComponentType<LucideProps>
  export const MoreVertical: ComponentType<LucideProps>
  export const Smile: ComponentType<LucideProps>
  export const Paperclip: ComponentType<LucideProps>
  export const Lock: ComponentType<LucideProps>
  export const Globe: ComponentType<LucideProps>
  export const Star: ComponentType<LucideProps>
  export const Reply: ComponentType<LucideProps>
  export const Pin: ComponentType<LucideProps>
  export const Bell: ComponentType<LucideProps>
  export const Menu: ComponentType<LucideProps>
  export const X: ComponentType<LucideProps>
  export const LogOut: ComponentType<LucideProps>
  export const Mail: ComponentType<LucideProps>
  export const Phone: ComponentType<LucideProps>
  export const MapPin: ComponentType<LucideProps>
  export const Home: ComponentType<LucideProps>
  export const ArrowLeft: ComponentType<LucideProps>
  export const ArrowRight: ComponentType<LucideProps>
  export const Stethoscope: ComponentType<LucideProps>
  export const GraduationCap: ComponentType<LucideProps>
  export const Shield: ComponentType<LucideProps>
  export const Award: ComponentType<LucideProps>
  export const Zap: ComponentType<LucideProps>
  export const EyeOff: ComponentType<LucideProps>
  export const CheckCircle: ComponentType<LucideProps>
  export const MessageCircle: ComponentType<LucideProps>
  export const Volume2: ComponentType<LucideProps>
  export const VolumeX: ComponentType<LucideProps>
  export const Bot: ComponentType<LucideProps>
  export const Loader2: ComponentType<LucideProps>
  export const Link: ComponentType<LucideProps>
  export const Share: ComponentType<LucideProps>
  export const MessageSquare: ComponentType<LucideProps>
  export const Copy: ComponentType<LucideProps>
  export const Check: ComponentType<LucideProps>
  export const AlertTriangle: ComponentType<LucideProps>
  export const Target: ComponentType<LucideProps>
  export const TrendingDown: ComponentType<LucideProps>
  export const Upload: ComponentType<LucideProps>
  export const Download: ComponentType<LucideProps>
  export const Lightbulb: ComponentType<LucideProps>
  export const UserPlus: ComponentType<LucideProps>
  export const Filter: ComponentType<LucideProps>
  export const Calendar: ComponentType<LucideProps>
  export const ThumbsUp: ComponentType<LucideProps>
  export const ThumbsDown: ComponentType<LucideProps>
  export const Share2: ComponentType<LucideProps>
  export const Flag: ComponentType<LucideProps>
  export const LinkIcon: ComponentType<LucideProps>
  export const XCircle: ComponentType<LucideProps>
  export const Play: ComponentType<LucideProps>
  export const Key: ComponentType<LucideProps>
  export const Crown: ComponentType<LucideProps>
  export const Maximize2: ComponentType<LucideProps>
  export const Minimize2: ComponentType<LucideProps>
  export const Image: ComponentType<LucideProps>
  export const Archive: ComponentType<LucideProps>
  export const ChevronLeft: ComponentType<LucideProps>
  export const ChevronRight: ComponentType<LucideProps>
  export const ChevronDown: ComponentType<LucideProps>
  export const ChevronUp: ComponentType<LucideProps>
  export const PieChart: ComponentType<LucideProps>
  export const LineChart: ComponentType<LucideProps>
  export const Printer: ComponentType<LucideProps>
}
